#!/bin/bash -e
read -p "Wprowadz nowa nazwe hosta (np. RPi4-[oznaczenie]): " NEW_HOSTNAME
CURRENT_HOSTNAME=`cat /etc/hostname | tr -d " \t\n\r"`
echo "Zmiana hostname z $CURRENT_HOSTNAME na $NEW_HOSTNAME..." >&2
echo $NEW_HOSTNAME | sudo tee /etc/hostname > /dev/null
sudo sed -i "s/127.0.1.1.*$CURRENT_HOSTNAME\$/127.0.1.1\t$NEW_HOSTNAME/g" /etc/hosts
echo "Hostname zmieniony na:" >&2
echo $NEW_HOSTNAME
rm -rf ~/.config/chromium/Singleton*
