#!/bin/bash
if sudo grep -q "Error connecting to XServer" /var/log/lightdm/lightdm.log
then
	echo "Restart Display after Error"    
	sudo service lightdm restart
else
	echo "Display is allready running"
fi
